{"name": "Wrong data authorization", "status": "passed", "steps": [{"name": "open the login page...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1715785055720, "stop": 1715785056014}], "start": 1715785055720, "stop": 1715785056014}, {"name": "log in with the faked username and password...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1715785056015, "stop": 1715785056024}, {"name": "fill in the fields...", "status": "passed", "start": 1715785056024, "stop": 1715785056106}, {"name": "click the login button...", "status": "passed", "start": 1715785056106, "stop": 1715785056142}], "start": 1715785056014, "stop": 1715785056142}, {"name": "check the current url and the error message is provided...", "status": "passed", "steps": [{"name": "get the current page url", "status": "passed", "start": 1715785056142, "stop": 1715785056146}], "start": 1715785056142, "stop": 1715785056146}, {"name": "take full screenshot in headless mode...", "status": "passed", "start": 1715785056147, "stop": 1715785056263}], "start": 1715785055720, "stop": 1715785056263, "uuid": "d26ea7ed-3cdb-4296-91ec-ab2c12ae93f6", "historyId": "937087821d0a9be90d29e9fef6ff4759", "testCaseId": "937087821d0a9be90d29e9fef6ff4759", "fullName": "tests.test_auth.TestLogin#test_fake_user_auth", "labels": [{"name": "as_id", "value": "1.5.1"}, {"name": "epic", "value": "Auth page"}, {"name": "feature", "value": "Auth"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "POLA-AI"}, {"name": "thread", "value": "18720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}