{"name": "Wrong data authorization", "status": "passed", "steps": [{"name": "open the login page...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1715784117662, "stop": 1715784117939}], "start": 1715784117662, "stop": 1715784117939}, {"name": "log in with the faked username and password...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1715784117940, "stop": 1715784117949}, {"name": "fill in the fields...", "status": "passed", "start": 1715784117949, "stop": 1715784118046}, {"name": "click the login button...", "status": "passed", "start": 1715784118046, "stop": 1715784118091}], "start": 1715784117939, "stop": 1715784118091}, {"name": "check the current url and the error message is provided...", "status": "passed", "steps": [{"name": "get the current page url", "status": "passed", "start": 1715784118091, "stop": 1715784118095}], "start": 1715784118091, "stop": 1715784118095}, {"name": "take full screenshot in headless mode...", "status": "passed", "start": 1715784118095, "stop": 1715784118216}], "start": 1715784117662, "stop": 1715784118216, "uuid": "6c0e57cf-f5a5-4730-8d08-4251bce8a115", "historyId": "937087821d0a9be90d29e9fef6ff4759", "testCaseId": "937087821d0a9be90d29e9fef6ff4759", "fullName": "tests.test_auth.TestLogin#test_fake_user_auth", "labels": [{"name": "as_id", "value": "1.5.1"}, {"name": "feature", "value": "Auth"}, {"name": "epic", "value": "Auth page"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "POLA-AI"}, {"name": "thread", "value": "17120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}